const alphabetResponse=await fetch('/alphabet.json'); const alphabet=await alphabetResponse.json();
const canvas=document.querySelector('#art');
const ctx=canvas.getContext('2d',{alpha:false});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const SIZE=512, library=new Map(), roots=[], actors=[], pending=[];
const rand=(a=0,b=1)=>a+Math.random()*(b-a), pick=a=>a[Math.floor(Math.random()*a.length)];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const smooth=x=>{x=clamp(x,0,1);return x*x*(3-2*x)};
const buffer=()=>Object.assign(document.createElement('canvas'),{width:SIZE,height:SIZE});
let w=innerWidth,h=innerHeight,dpr=1,time=0,last=0,paused=false,nextBirth=22,nextLayout=75;
let inverted=false,mode=0,pointer={x:.5,y:.5,active:false,down:false,vx:0,vy:0},impulse=0,saving=false,archiveCursor=null;
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
resize();addEventListener('resize',resize);
function snapshot(path){const c=buffer(),g=c.getContext('2d');g.translate(SIZE/2,SIZE/2);g.scale(SIZE*.9,SIZE*.9);g.fill(new Path2D(path));return c}
function whiteVersion(source){const c=buffer(),g=c.getContext('2d');g.drawImage(source,0,0);g.globalCompositeOperation='source-in';g.fillStyle='#fff';g.fillRect(0,0,SIZE,SIZE);return c}
for(const form of alphabet){const black=snapshot(form.path);const f={...form,generation:0,black,white:whiteVersion(black),persisted:true};roots.push(f);library.set(f.id,f)}
function spawn(form,options={}){
 const a={form,x:options.x??rand(.02,.98),y:options.y??rand(.04,.96),angle:rand(-.8,.8),spin:rand(-.12,.12),vx:rand(-.038,.038),vy:rand(-.032,.032),jiggle:0,jiggleV:0,scale:rand(.1,.28),phase:rand(0,Math.PI*2),birth:time,fadeAt:null,fadeDuration:rand(95,165),opacity:1,...options};
 if(actors.length>=30){let old=actors.findIndex(x=>x.fadeAt!==null&&!x.letterSlot&&!x.letterReserved);if(old<0)old=actors.findIndex(x=>!x.letterSlot&&!x.letterReserved);if(old>=0)actors.splice(old,1)}actors.push(a);return a;
}
const initial=[0,3,4,10,11,12,13,14,15,16,1,8];
initial.forEach((i,j)=>spawn(roots[i],{x:.09+(j*.618034)%.84,y:.11+(j*.381966)%.77,scale:j===5?.39:rand(.12,.25),birth:-8,angle:rand(-.32,.32)}));
function transform(c,source,t){c.save();c.translate(SIZE*(.5+t.x),SIZE*(.5+t.y));c.rotate(t.rotation);c.scale(t.sx,t.sy);c.drawImage(source,-SIZE/2,-SIZE/2);c.restore()}
function mutation(a,b){
 const operations=['join','cut','intersect','negative','nest','repeat','split','stretch'];
 const operation=pick(operations),c=buffer(),g=c.getContext('2d',{willReadFrequently:true});
 const t1={x:rand(-.11,.07),y:rand(-.09,.09),rotation:rand(-.55,.55),sx:rand(.57,.85),sy:rand(.62,.9)};
 const t2={x:rand(-.12,.19),y:rand(-.15,.15),rotation:rand(-2.1,2.1),sx:rand(.38,.8)*(Math.random()<.2?-1:1),sy:rand(.4,.85)};
 transform(g,a.black,t1);
 if(operation==='cut'||operation==='nest'){g.globalCompositeOperation='destination-out';if(operation==='nest'){t2.x=t1.x;t2.y=t1.y;t2.sx=t1.sx*.62;t2.sy=t1.sy*.62}transform(g,b.black,t2)}
 else if(operation==='intersect'){g.globalCompositeOperation='destination-in';transform(g,b.black,t2)}
 else if(operation==='negative'){g.globalCompositeOperation='xor';transform(g,b.black,t2)}
 else if(operation==='repeat'){for(let i=1;i<4;i++)transform(g,a.black,{...t1,x:t1.x+i*.13,y:t1.y-i*.07,sx:t1.sx*.64,sy:t1.sy*.64})}
 else if(operation==='split'){g.globalCompositeOperation='destination-out';Object.assign(t2,{sx:.2,sy:1.25});transform(g,b.black,t2)}
 else if(operation==='stretch'){g.clearRect(0,0,SIZE,SIZE);Object.assign(t1,{sx:rand(.27,.5),sy:rand(.9,1.5)});transform(g,a.black,t1)}
 else transform(g,b.black,t2);
 const data=g.getImageData(0,0,SIZE,SIZE).data;let xmin=SIZE,ymin=SIZE,xmax=0,ymax=0,count=0;
 for(let y=0;y<SIZE;y+=3)for(let x=0;x<SIZE;x+=3)if(data[(y*SIZE+x)*4+3]>100){xmin=Math.min(xmin,x);xmax=Math.max(xmax,x);ymin=Math.min(ymin,y);ymax=Math.max(ymax,y);count++}
 const bw=xmax-xmin,bh=ymax-ymin;if(count<155||bw<27||bh<27||count/(SIZE*SIZE/9)>.72)return null;
 const normalized=buffer(),ng=normalized.getContext('2d'),s=SIZE*.9/Math.max(bw,bh);ng.drawImage(c,xmin,ymin,bw+3,bh+3,(SIZE-bw*s)/2,(SIZE-bh*s)/2,bw*s,bh*s);
 const parents=operation==='repeat'||operation==='stretch'?[a.id]:[a.id,b.id];
 return {id:`${9999999999999-Date.now()}-${crypto.randomUUID()}`,generation:1+Math.max(a.generation,...(parents.length>1?[b.generation]:[])),parents,operation,transforms:[t1,t2],black:normalized,white:whiteVersion(normalized),persisted:false,createdAt:Date.now()};
}
function breed(near){const eligible=actors.filter(a=>a.form.persisted&&(a.fadeAt===null||time-a.fadeAt<45));let a,b;if(near){eligible.sort((a,b)=>Math.hypot(a.x-near.x,a.y-near.y)-Math.hypot(b.x-near.x,b.y-near.y));a=eligible[0];b=eligible[1]}else{a=pick(eligible);b=pick(eligible.filter(x=>x!==a))}const archive=[...library.values()].filter(f=>f.persisted&&f.generation>0);const first=!near&&archive.length&&Math.random()<.58?pick(archive):(a?.form??pick(roots));const second=b?.form??pick(roots);let child=null;for(let attempt=0;attempt<4&&!child;attempt++)child=mutation(first,second);if(!child)return null;library.set(child.id,child);const actor=spawn(child,{x:near?.x??a?.x??rand(.12,.88),y:near?.y??a?.y??rand(.1,.9),scale:rand(.19,.34)});for(const p of [a,b])if(p){p.fadeAt=time;p.fadeDuration=rand(65,115)}pending.push({form:child,actor});void savePending();trimLibrary();return child.id}
async function savePending(){if(saving||!pending.length)return;saving=true;try{const {form,actor}=pending[0];const response=await fetch('/api/forms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:form.id,parents:form.parents,operation:form.operation,transforms:form.transforms,png:form.black.toDataURL('image/png')})});if(!response.ok)throw Error(`Archive save ${response.status}`);const result=await response.json();form.persisted=true;form.generation=result.generation;pending.shift();actor.fadeAt=time+14;actor.fadeDuration=rand(110,180)}catch(error){console.warn('The archive is temporarily unavailable; the living form is retained for retry.',error)}finally{saving=false}}
function trimLibrary(){const protectedIds=new Set([...roots.map(f=>f.id),...actors.map(a=>a.form.id),...pending.map(p=>p.form.id)]);for(const [id,f] of library){if(library.size<=64)break;if(!protectedIds.has(id)){f.black.width=1;f.white.width=1;library.delete(id)}}}
async function loadArchive(more=false){try{const response=await fetch('/api/forms'+(more&&archiveCursor?'?cursor='+encodeURIComponent(archiveCursor):''));if(!response.ok)throw Error(`Archive load ${response.status}`);const saved=await response.json();archiveCursor=saved.cursor??null;await Promise.all(saved.forms.map(async record=>{if(library.has(record.id))return;const img=new Image();img.src=record.png;await img.decode();const black=buffer();black.getContext('2d').drawImage(img,0,0,SIZE,SIZE);const f={...record,black,white:whiteVersion(black),persisted:true};library.set(f.id,f)}));trimLibrary();if(!more){const memories=[...library.values()].filter(f=>f.generation>0);for(const f of memories.slice(0,4))spawn(f,{opacity:rand(.09,.22),birth:-10,fadeAt:time,fadeDuration:160,scale:rand(.2,.4)})}}catch(error){console.warn('Continuing with the original alphabet until the archive reconnects.',error)}}
void loadArchive();setInterval(()=>{void savePending();if(library.size===roots.length)void loadArchive()},18000);addEventListener('online',()=>{void savePending();void loadArchive()});
function newArrangement(){mode=(mode+1+Math.floor(rand(0,3)))%5;nextLayout=time+rand(65,110);if(archiveCursor)void loadArchive(true)}
function target(a,i){if(mode===1)return{x:.5+Math.cos(a.phase)*.2,y:.5+Math.sin(a.phase)*.26};if(mode===2)return{x:.15+(i%4)*.24,y:.12+Math.floor(i/4)*.25};if(mode===3)return{x:.5+Math.cos(a.phase)*.55,y:.5+Math.sin(a.phase)*.5};if(mode===4)return{x:.5+Math.sin(a.phase)*.14,y:.1+(i%9)*.1};return null}
const letterScores={A:[[[0,1],[.5,0],[1,1]],[[.23,.56],[.77,.56]]],B:[[[0,1],[0,0],[.65,0],[.94,.12],[.94,.35],[.66,.49],[0,.49]],[[.66,.49],[1,.61],[1,.85],[.68,1],[0,1]]],C:[[[1,.12],[.75,0],[.25,0],[0,.2],[0,.8],[.25,1],[.75,1],[1,.88]]],D:[[[0,1],[0,0],[.58,0],[.91,.2],[1,.5],[.91,.8],[.58,1],[0,1]]],E:[[[1,0],[0,0],[0,1],[1,1]],[[0,.5],[.8,.5]]],F:[[[0,1],[0,0],[1,0]],[[0,.48],[.8,.48]]],G:[[[1,.16],[.75,0],[.25,0],[0,.2],[0,.8],[.25,1],[.8,1],[1,.8],[1,.55],[.55,.55]]],H:[[[0,0],[0,1]],[[1,0],[1,1]],[[0,.5],[1,.5]]],I:[[[.12,0],[.88,0]],[[.5,0],[.5,1]],[[.12,1],[.88,1]]],J:[[[.3,0],[1,0]],[[.85,0],[.85,.8],[.65,1],[.22,1],[0,.8]]],K:[[[0,0],[0,1]],[[1,0],[0,.53],[1,1]]],L:[[[0,0],[0,1],[1,1]]],M:[[[0,1],[0,0],[.5,.55],[1,0],[1,1]]],N:[[[0,1],[0,0],[1,1],[1,0]]],O:[[[.25,0],[.75,0],[1,.23],[1,.77],[.75,1],[.25,1],[0,.77],[0,.23],[.25,0]]],P:[[[0,1],[0,0],[.7,0],[1,.15],[1,.4],[.7,.55],[0,.55]]],Q:[[[.25,0],[.75,0],[1,.23],[1,.72],[.75,.94],[.25,.94],[0,.72],[0,.23],[.25,0]],[[.6,.68],[1.05,1.06]]],R:[[[0,1],[0,0],[.7,0],[1,.15],[1,.38],[.7,.52],[0,.52]],[[.5,.52],[1,1]]],S:[[[1,.13],[.75,0],[.25,0],[0,.16],[0,.35],[.25,.48],[.75,.52],[1,.65],[1,.84],[.75,1],[.25,1],[0,.87]]],T:[[[0,0],[1,0]],[[.5,0],[.5,1]]],U:[[[0,0],[0,.76],[.22,1],[.78,1],[1,.76],[1,0]]],V:[[[0,0],[.5,1],[1,0]]],W:[[[0,0],[.22,1],[.5,.47],[.78,1],[1,0]]],X:[[[0,0],[1,1]],[[1,0],[0,1]]],Y:[[[0,0],[.5,.5],[1,0]],[[.5,.5],[.5,1]]],Z:[[[0,0],[1,0],[0,1],[1,1]]]};
let letter=null,nextLetterAt=12,letterIndex=0;
function beginLetter(){const name=Object.keys(letterScores)[letterIndex++%26],slots=[];for(const line of letterScores[name])for(let i=1;i<line.length;i++){const[x0,y0]=line[i-1],[x1,y1]=line[i],dx=x1-x0,dy=(y1-y0)*1.25;const length=Math.hypot(dx,dy),count=Math.ceil(length/.25);for(let j=0;j<count;j++)slots.push({x:x0+(x1-x0)*(j+.5)/count,y:y0+(y1-y0)*(j+.5)/count,length:length/count,angle:Math.atan2(dy,dx)-Math.PI/2})}const available=actors.filter(a=>a.opacity>.3&&a!==dragged&&(a.fadeAt===null||time-a.fadeAt<a.fadeDuration*.4)).slice(0,slots.length);for(const a of available)a.letterReserved=true;while(available.length<slots.length)available.push(spawn(pick(roots),{scale:rand(.12,.21),letterReserved:true}));letter={name,start:time,slots};for(const slot of slots){const a=available.shift();delete a.letterReserved;a.letterSlot=slot;a.letterRestUntil=0;if(a.fadeAt!==null)a.fadeAt=Math.max(a.fadeAt,time+27-a.fadeDuration*.2)}canvas.dataset.letter=name}
function letterStrength(){if(!letter)return 0;const age=time-letter.start;return smooth(age/7)*(1-smooth((age-23)/7))}
function inkBounds(form){if(form.ink)return form.ink;const data=form.black.getContext('2d').getImageData(0,0,SIZE,SIZE).data;let x0=SIZE,y0=SIZE,x1=0,y1=0;for(let y=0;y<SIZE;y+=2)for(let x=0;x<SIZE;x+=2)if(data[(y*SIZE+x)*4+3]>30){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y)}return form.ink={x:x0,y:y0,w:Math.max(1,x1-x0+2),h:Math.max(1,y1-y0+2)}}
function letterPosition(slot){const unit=Math.min(w*.68,h*.60);return{x:w/2+(slot.x-.5)*unit,y:h/2+(slot.y-.5)*unit*1.25,width:unit*.13,height:slot.length*unit*1.38,angle:slot.angle}}
function pose(a){const ink=inkBounds(a.form),breath=reduced?1:1+Math.sin(time*1.6+a.phase)*.045;const size=a.scale*Math.min(w,h)*1.65*breath*(mode===3?1.4:1);const wobble=reduced?0:Math.sin(time*2.4+a.phase)*.048+a.jiggle;const p={x:a.x*w+(reduced?0:Math.sin(time*1.3+a.phase)*9),y:a.y*h+(reduced?0:Math.cos(time*1.1+a.phase)*9),angle:a.angle+(reduced?0:Math.sin(time*1.9+a.phase)*.08+a.jiggle*.5),width:size*ink.w/SIZE*(1+wobble),height:size*ink.h/SIZE/(1+wobble),ambient:1};const strength=letterStrength();if(a.letterSlot&&a!==dragged){const mix=strength*smooth((time-(a.letterRestUntil||0))/3),t=letterPosition(a.letterSlot);p.x+=(t.x-p.x)*mix;p.y+=(t.y-p.y)*mix;p.width+=(t.width*(1+wobble*.23)-p.width)*mix;p.height+=(t.height/(1+wobble*.23)-p.height)*mix;p.angle+=Math.atan2(Math.sin(t.angle-p.angle),Math.cos(t.angle-p.angle))*mix}else if(letter&&a!==dragged)p.ambient=1-strength*.88;return p}
function frame(now){const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(!paused&&!document.hidden)time+=dt;if(!paused&&!document.hidden){if(!letter&&time>=nextLetterAt)beginLetter();if(letter&&time-letter.start>=30){for(const a of actors)if(a.letterSlot){delete a.letterSlot;a.jiggleV+=rand(-2,2);a.vx+=rand(-.035,.035);a.vy+=rand(-.035,.035)}letter=null;nextLetterAt=time+rand(19,29);delete canvas.dataset.letter}if(time>nextBirth&&!letter){breed();nextBirth=time+rand(reduced?40:19,reduced?60:31);if(actors.filter(a=>a.fadeAt===null).length<7)spawn(pick(roots));if(Math.random()<.35){const archived=[...library.values()].filter(f=>f.persisted&&f.generation>0);if(archived.length)spawn(pick(archived),{opacity:.65,fadeAt:time+18})}}if(time>nextLayout)newArrangement()}ctx.fillStyle='#292929';ctx.fillRect(0,0,w,h);for(let i=actors.length-1;i>=0;i--){const a=actors[i],age=time-a.birth,fade=a.fadeAt===null?1:1-smooth((time-a.fadeAt)/a.fadeDuration);if(fade<=.0001){actors.splice(i,1);continue}if(!paused&&!document.hidden&&!reduced){if(a.letterSlot&&a!==dragged&&time>(a.letterRestUntil||0)){const goal=letterPosition(a.letterSlot),pull=letterStrength();a.vx+=((goal.x/w-a.x)*12-a.vx*5)*dt*pull;a.vy+=((goal.y/h-a.y)*12-a.vy*5)*dt*pull}const t=target(a,i);if(t){a.vx+=(t.x-a.x)*dt*.009;a.vy+=(t.y-a.y)*dt*.009}if(pointer.active&&a!==dragged){const dx=(a.x-pointer.x)*w,dy=(a.y-pointer.y)*h,dist=Math.hypot(dx,dy),radius=Math.min(w,h)*.32;if(dist<radius&&dist>1){const influence=1-dist/radius;a.vx+=(dx/dist*.19+pointer.vx*.18)*influence*dt;a.vy+=(dy/dist*.19+pointer.vy*.18)*influence*dt;a.jiggleV+=influence*Math.min(1,Math.hypot(pointer.vx,pointer.vy))*dt*12}}if(a===dragged){a.vx+=((pointer.x+grabOffset.x-a.x)*32-a.vx*8)*dt;a.vy+=((pointer.y+grabOffset.y-a.y)*32-a.vy*8)*dt;a.jiggleV+=Math.min(1,Math.hypot(pointer.vx,pointer.vy))*dt*10}else{a.vx+=Math.sin(time*.9+a.phase)*dt*.004;a.vy+=Math.cos(time*.73+a.phase)*dt*.004}const damping=Math.exp(-dt*(a===dragged?.3:.18));a.vx=clamp(a.vx*damping,-.4,.4);a.vy=clamp(a.vy*damping,-.4,.4);a.x+=a.vx*dt;a.y+=(a.vy+impulse*.025)*dt;a.angle+=a.spin*dt;const edge=mode===3?-.08:.025;if(a.x<edge){a.x=edge;a.vx=Math.abs(a.vx)*.9+.014;a.jiggleV+=2.6}if(a.x>1-edge){a.x=1-edge;a.vx=-Math.abs(a.vx)*.9-.014;a.jiggleV-=2.6}if(a.y<edge){a.y=edge;a.vy=Math.abs(a.vy)*.9+.012;a.jiggleV+=2.6}if(a.y>1-edge){a.y=1-edge;a.vy=-Math.abs(a.vy)*.9-.012;a.jiggleV-=2.6}a.jiggleV+=(-a.jiggle*65-a.jiggleV*5.5)*dt;a.jiggle=clamp(a.jiggle+a.jiggleV*dt,-.45,.45)}const p=pose(a),ink=inkBounds(a.form);const opacity=smooth(age/3)*fade*a.opacity*p.ambient;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.globalAlpha=opacity;ctx.drawImage(inverted?a.form.black:a.form.white,ink.x,ink.y,ink.w,ink.h,-p.width/2,-p.height/2,p.width,p.height);ctx.restore()}impulse*=Math.exp(-dt*2);pointer.vx*=Math.exp(-dt*7);pointer.vy*=Math.exp(-dt*7);requestAnimationFrame(frame)}
requestAnimationFrame(frame);
let clickAt=-20,dragged=null,grabOffset={x:0,y:0},pressStart=null,lastPointerAt=0;
function hitForm(x,y){for(const a of actors){if(a.opacity<.3||(a.fadeAt!==null&&time-a.fadeAt>a.fadeDuration*.7))continue;const p=pose(a),ink=inkBounds(a.form);if(p.ambient<.3)continue;const dx=x*w-p.x,dy=y*h-p.y,cos=Math.cos(-p.angle),sin=Math.sin(-p.angle);const px=Math.floor(ink.x+((dx*cos-dy*sin)/p.width+.5)*ink.w),py=Math.floor(ink.y+((dx*sin+dy*cos)/p.height+.5)*ink.h);if(px>=0&&px<SIZE&&py>=0&&py<SIZE&&a.form.black.getContext('2d').getImageData(px,py,1,1).data[3]>80)return a}return null}
canvas.addEventListener('pointermove',e=>{const x=e.clientX/w,y=e.clientY/h,now=performance.now(),elapsed=Math.max((now-lastPointerAt)/1000,.016);pointer.vx=clamp((x-pointer.x)/elapsed,-3,3);pointer.vy=clamp((y-pointer.y)/elapsed,-3,3);Object.assign(pointer,{x,y,active:true});lastPointerAt=now;if(reduced&&dragged){dragged.x=x+grabOffset.x;dragged.y=y+grabOffset.y}canvas.style.cursor=dragged?'grabbing':hitForm(x,y)?'grab':'default'});
canvas.addEventListener('pointerdown',e=>{if(paused)return;const x=e.clientX/w,y=e.clientY/h;Object.assign(pointer,{x,y,active:true,down:true});pressStart={x:e.clientX,y:e.clientY};const grabbed=hitForm(x,y),visible=grabbed?pose(grabbed):null;dragged=grabbed;if(dragged){dragged.x=visible.x/w;dragged.y=visible.y/h;dragged.letterRestUntil=time+5;grabOffset={x:dragged.x-x,y:dragged.y-y};dragged.jiggleV+=3;canvas.style.cursor='grabbing'}canvas.setPointerCapture(e.pointerId)});
function release(e,cancelled=false){const wasDrag=pressStart&&Math.hypot(e.clientX-pressStart.x,e.clientY-pressStart.y)>7;if(dragged){dragged.letterRestUntil=time+4;if(!reduced){dragged.vx=clamp(dragged.vx+pointer.vx*.2,-.4,.4);dragged.vy=clamp(dragged.vy+pointer.vy*.2,-.4,.4);dragged.jiggleV+=3}dragged=null}pointer.down=false;pressStart=null;canvas.style.cursor='default';if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(cancelled||paused)return;if(!wasDrag){const x=e.clientX/w,y=e.clientY/h;if(!reduced)for(const a of actors){const dx=a.x-x,dy=a.y-y,dist=Math.hypot(dx,dy);if(dist<.5&&dist>.001){a.vx+=dx/dist*.12*(1-dist/.5);a.vy+=dy/dist*.12*(1-dist/.5);a.jiggleV+=5*(1-dist/.5)}}if(time-clickAt>2.5){clickAt=time;breed({x,y})}}}
canvas.addEventListener('pointerup',e=>release(e));canvas.addEventListener('pointercancel',e=>release(e,true));canvas.addEventListener('pointerleave',()=>{if(!pointer.down)pointer.active=false});canvas.addEventListener('wheel',e=>{e.preventDefault();impulse=clamp(impulse+e.deltaY*.003,-2,2);if(!reduced)for(const a of actors)a.jiggleV+=clamp(e.deltaY*.012,-1.2,1.2)},{passive:false});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();paused=!paused}if(e.key.toLowerCase()==='i')inverted=!inverted});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'combine_nearby_forms',description:'Combine two nearby forms in the living artwork and preserve their descendant in its archive.',inputSchema:{type:'object',properties:{x:{type:'number',minimum:0,maximum:1},y:{type:'number',minimum:0,maximum:1}},required:['x','y'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({x,y})=>{if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||x>1||y<0||y>1)throw Error('Coordinates must be between 0 and 1');const id=breed({x,y});return{created:!!id,id,archiveStatus:'queued'}}})}catch(error){console.warn(error)}}
